//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace deal.repository.entityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public Company()
        {
            this.CompanySubsidiaries = new HashSet<CompanySubsidiary>();
            this.CompanyUsers = new HashSet<CompanyUser>();
        }
    
        public int companyId { get; set; }
        public string companyName { get; set; }
    
        public virtual ICollection<CompanySubsidiary> CompanySubsidiaries { get; set; }
        public virtual ICollection<CompanyUser> CompanyUsers { get; set; }
    }
}
