//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace deal.repository.entityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class DealResponse
    {
        public int dealResponseId { get; set; }
        public int serviceRequestId { get; set; }
        public int responseById { get; set; }
        public System.DateTime responseDate { get; set; }
        public string responseComment { get; set; }
    
        public virtual ServiceRequest ServiceRequest { get; set; }
        public virtual UserRole UserRole { get; set; }
    }
}
