//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace deal.repository.entityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceType
    {
        public ServiceType()
        {
            this.CompanyServices = new HashSet<CompanyService>();
            this.ServiceRequests = new HashSet<ServiceRequest>();
        }
    
        public int serviceTypeId { get; set; }
        public string serviceTypeDescription { get; set; }
    
        public virtual ICollection<CompanyService> CompanyServices { get; set; }
        public virtual ICollection<ServiceRequest> ServiceRequests { get; set; }
    }
}
