//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace deal.repository.entityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceRequestStatusType
    {
        public int serviceRequestStatusTypeId { get; set; }
        public int serviceRequestId { get; set; }
        public int requestStatusTypeId { get; set; }
        public System.DateTime fromDate { get; set; }
        public Nullable<System.DateTime> toDate { get; set; }
    
        public virtual ServiceRequest ServiceRequest { get; set; }
    }
}
