//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace deal.repository.entityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceRequest
    {
        public ServiceRequest()
        {
            this.DealResponses = new HashSet<DealResponse>();
            this.ServiceRequestStatusTypes = new HashSet<ServiceRequestStatusType>();
        }
    
        public int serviceRequestId { get; set; }
        public int serviceTypeId { get; set; }
        public int requestById { get; set; }
        public System.DateTime requestDate { get; set; }
        public string requestDescription { get; set; }
        public decimal requestBudgetFrom { get; set; }
        public decimal requestBudgetTo { get; set; }
        public int serviceRequestCityId { get; set; }
    
        public virtual ICollection<DealResponse> DealResponses { get; set; }
        public virtual ServiceType ServiceType { get; set; }
        public virtual StateCity StateCity { get; set; }
        public virtual UserRole UserRole { get; set; }
        public virtual ICollection<ServiceRequestStatusType> ServiceRequestStatusTypes { get; set; }
    }
}
