//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace deal.repository.entityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class StateCity
    {
        public StateCity()
        {
            this.ServiceRequests = new HashSet<ServiceRequest>();
        }
    
        public int stateCityId { get; set; }
        public int stateId { get; set; }
        public string cityDescription { get; set; }
    
        public virtual ICollection<ServiceRequest> ServiceRequests { get; set; }
        public virtual State State { get; set; }
    }
}
