//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace deal.repository.entityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class State
    {
        public State()
        {
            this.StateCities = new HashSet<StateCity>();
            this.UserStateLocations = new HashSet<UserStateLocation>();
        }
    
        public int stateId { get; set; }
        public string stateDescription { get; set; }
        public string stateLetter { get; set; }
    
        public virtual ICollection<StateCity> StateCities { get; set; }
        public virtual ICollection<UserStateLocation> UserStateLocations { get; set; }
    }
}
