//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace deal.repository.entityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRole
    {
        public UserRole()
        {
            this.CompanyUsers = new HashSet<CompanyUser>();
            this.DealResponses = new HashSet<DealResponse>();
            this.ServiceRequests = new HashSet<ServiceRequest>();
            this.UserStateLocations = new HashSet<UserStateLocation>();
        }
    
        public int userRoleId { get; set; }
        public int userId { get; set; }
        public int roleId { get; set; }
        public System.DateTime fromDate { get; set; }
        public Nullable<System.DateTime> toDate { get; set; }
    
        public virtual ICollection<CompanyUser> CompanyUsers { get; set; }
        public virtual ICollection<DealResponse> DealResponses { get; set; }
        public virtual Role Role { get; set; }
        public virtual ICollection<ServiceRequest> ServiceRequests { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<UserStateLocation> UserStateLocations { get; set; }
    }
}
